import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import QueryProvider from "@/lib/react-query/QueryProvider";
import { AuthProvider } from "@/lib/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`inter.className bg-[#09080d] text-[#f9f9f9]`}>
				<QueryProvider>
					<AuthProvider>
						<Navbar />
						{children}
						<Toaster />
					</AuthProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
